### ISSUE TITLE
javascript loader doesn't support custom content

### ISSUE THREAD

**Issue by jheyer159** [cosmiconfig/cosmiconfig#258]
This `loadJS` function doesn't have a content parameter.
https://github.com/davidtheclark/cosmiconfig/blob/18346056c9a7fdf8d7531ea5a998edfb255fc140/src/loaders.ts#L10

`loadJson` and `loadYaml ` both support custom content
https://github.com/davidtheclark/cosmiconfig/blob/18346056c9a7fdf8d7531ea5a998edfb255fc140/src/loaders.ts#L20
https://github.com/davidtheclark/cosmiconfig/blob/18346056c9a7fdf8d7531ea5a998edfb255fc140/src/loaders.ts#L35

Is this intended?

**Comment by davidtheclark** [comment]
Hi @jheyer159. The `loadJS` implementation uses `require`, relying on Node.js to parse the JS, so it doesn't have a way to handle a `content` parameter where you'd pass a raw JS string. You could write a custom loader for this, using an npm package like https://www.npmjs.com/package/require-from-string. (That's [how cosmiconfig did it a while ago](https://github.com/davidtheclark/cosmiconfig/blob/b9b532b2329bd8caada40aebd2bb76d8c5558c86/src/parser.js#L8-L10), but we ran into some troubles with it as a generic solution.)
