### ISSUE TITLE
Export `defaultSearchPlaces` like `defaultLoaders` for reusing

### ISSUE THREAD

**Issue by JounQin** [cosmiconfig/cosmiconfig#264]
As title

So that use with other loaders like [`@endemolshinegroup/cosmiconfig-typescript-loader`](https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader) will be simpler.

**Comment by d-fischer** [comment]
Is there any actual problem here? cosmiconfig always uses all default loaders unless you overwrite an existing extension.

**Comment by RichiCoder1** [comment]
Would a new option like `plugins` with this API make sense?

```
{
  loaders: () => Record<string, Loader>,
  searchPlaces: (moduleName: string) => string[]
}[]
```

**Comment by d-fischer** [comment]
9.0.0 will include `getDefaultSearchPlaces` and `getDefaultSearchPlacesSync`.
