### ISSUE TITLE
8.0.0 -> 8.1.0 breaks  with TypeError when using Rollup

### ISSUE THREAD

**Issue by Jason3S** [cosmiconfig/cosmiconfig#291]
I'm not sure why upgrading to 8.1.0 breaks things. Or even why chalk would get included.

```js
ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
                                                                          ^

TypeError: Cannot read properties of undefined (reading 'close')
```

```
cspell-lib link:../../../packages/cspell-lib
└─┬ cosmiconfig 8.1.0
  └─┬ parse-json 5.2.0
    └─┬ @babel/code-frame 7.18.6
      └─┬ @babel/highlight 7.18.6
        └── chalk 2.4.2
cspell-lib link:../../../packages/cspell-lib
└─┬ cosmiconfig 8.1.0
  └─┬ parse-json 5.2.0
    └─┬ @babel/code-frame 7.18.6
      └─┬ @babel/highlight 7.18.6
        └─┬ chalk 2.4.2
          └── ansi-styles 3.2.1
```
```
cspell-lib link:../../../packages/cspell-lib
└─┬ cosmiconfig 8.0.0
  └─┬ parse-json 5.2.0
    └─┬ @babel/code-frame 7.18.6
      └─┬ @babel/highlight 7.18.6
        └── chalk 2.4.2
cspell-lib link:../../../packages/cspell-lib
└─┬ cosmiconfig 8.0.0
  └─┬ parse-json 5.2.0
    └─┬ @babel/code-frame 7.18.6
      └─┬ @babel/highlight 7.18.6
        └─┬ chalk 2.4.2
          └── ansi-styles 3.2.1
```

**Comment by d-fischer** [comment]
That's weird, there were no changes to any of the dependencies in package.json in 8.1.0.

Can you provide a full reproduction case (optimally just as a github repo I can easily clone and run to see the error) for this?

**Comment by d-fischer** [comment]
I tracked this down to a change in `@rollup/plugin-commonjs`. Version `23.0.4` works, everything past it does not. It seems to be due to [this PR](https://github.com/rollup/plugins/pull/1363).

Please open an issue in [rollup's repository](https://github.com/rollup/plugins).

If they refuse to fix this for some reason, the package having to adapt would probably be `chalk` or `ansi-styles`, not `cosmiconfig`.

**Comment by Jason3S** [comment]
@d-fischer,

Thank you for looking into it.
