### ISSUE TITLE
Make it possible to import parts of your configuration from other files

### ISSUE THREAD

**Issue by d-fischer** [cosmiconfig/cosmiconfig#292]
## What

People should be able to import base configuration files which your configuration will then be merged into.

#### .config/prettier.base.yml
```yml
printWidth: 80
semi: true
```

#### packages/foo/.config/prettier.yml
```yml
$import: ../../../.config/prettier.base.yml
# or as an array:
$import:
  - ../../../.config/prettier.base.yml
tabWidth: 4
useTabs: true
printWidth: 120
```

#### Resulting configuration object
```js
{
  semi: true,
  tabWidth: 4,
  useTabs: true,
  printWidth: 120
}
```

## Why

This is mostly to overcome possible limitations outlined in #152, but can also be used to share configuration using an npm package, and I'm sure there's a few more applications for this.

## Additional requirements

- The `$import` special key should instruct the loader to load the given file(s) using the same explorer the consumer used, and merge your own configuration into it
- Your own configuration should take priority over any imported file(s)
- `$import` should be able to contain a string directly, or an array of strings
- When importing multiple files, the last one takes priority
- Nested importing should be possible, i.e. you should be able to `$import` a configuration file which itself uses `$import`
- There should be a circular dependency check - loops of any size should lead to an error being thrown
- You should be able to `$import` files of a different format than the one you're using
- There should be a configuration option for the consumer that determines how to handle arrays on the same object key (concat/overwrite/possibly more use cases you have to tell me about because I can't imagine any more?)

Related to #152

**Comment by RichiCoder1** [comment]
Howdy, just stumbling across this issue!

Had two clarifying questions:
1) Would the special `$import` key work for all supported formats (including js)?
2) Irt merging logic, it might be worth using https://github.com/survivejs/webpack-merge (or it's same logic) as it's fairly battle-tested when it comes to specifically configuration merging.

**Comment by d-fischer** [comment]
> 1. Would the special `$import` key work for all supported formats (including js)?

You should be able to import any supported format from any supported format. `cosmiconfig` will just parse the end result and then recurse back into the file loader.

> 2. Irt merging logic, it might be worth using https://github.com/survivejs/webpack-merge (or it's same logic) as it's fairly battle-tested when it comes to specifically configuration merging. Maybe with an extensibility point to override the merge logic?

In its current state, there's just a mostly naive merge algorithm. I might consider a smarter, more configurable approach later.

**Comment by jrandolf** [comment]
I'm not sure this kind of feature would be desirable among all dependent packages. In particular, it's polluting the configuration file with reserved names which should really be up to the user.

**Comment by d-fischer** [comment]
> I'm not sure this kind of feature would be desirable among all dependent packages.

This is related to a discussion in #152. (I forgot adding this to the OP, will do now)

> In particular, it's polluting the configuration file with reserved names which should really be up to the user.

If you have a better idea on how to implement this feature, don't hesitate to weigh in on said discussion.

**Comment by d-fischer** [comment]
Merged into new `v9` branch where the other new features will also be added. Closing this.
