### ISSUE TITLE
Possible Unintended Side Effects of: always look at `.config.{yml,yaml,json,js,cjs}`

### ISSUE THREAD

**Issue by Jason3S** [cosmiconfig/cosmiconfig#296]
> ## 8.1.0
>
> - Added: always look at `.config.{yml,yaml,json,js,cjs}` file to configure cosmiconfig itself, and look for tool configuration in it using `packageProp` (similar to package.json)
>  - For more info on this, look at the [end user configuration section of the README](https://github.com/cosmiconfig/cosmiconfig/blob/main/README.md#usage-for-end-users)

Is there a way to turn this off? I'm hunting down a crashing issue https://github.com/streetsidesoftware/vscode-spell-checker/issues/2583 that is most likely caused by a user's `.config.*` changing the `.json` parser.

**Comment by d-fischer** [comment]
You can explicitly not overwrite `loaders` in that config file (as of now): https://github.com/cosmiconfig/cosmiconfig/blob/dacce131ed0d8e121d3155e5922bfb4998822187/src/index.ts#L125-L127

This might be a bug relating to the loading though. Will investigate as soon as your user has answered your question in your issue so I have a proper lead on this.

**Comment by Jason3S** [comment]
@d-fischer,

He has confirmed that there is a `.config.js`: https://github.com/streetsidesoftware/vscode-spell-checker/issues/2583#issuecomment-1473284396

The issue is right there in the code, `options` is lost if there is a `metaConfig`:
https://github.com/cosmiconfig/cosmiconfig/blob/dacce131ed0d8e121d3155e5922bfb4998822187/src/index.ts#L119-L138

**Comment by Jason3S** [comment]
@d-fischer,

Does it make sense to "merger" the `searchPlaces` instead of replacing them? I can understand if a User wants to **add** their preferred places, but replacing the ones specified by the cli-tool can easily cause things to break.

For example, `cspell` has multiple places for a configuration file. It has a defined search pattern. Sub folders and parent folders might both have config files. If the `.config.js` at the root is there to clean up the root, it would mess up the sub folders.

Case in point, if someone adds a `.config.js` to adjust the location of prettier, they could break `cspell` or `eslint` because a "single" config is applied to ALL tools that use Cosmiconfig.

**Comment by d-fischer** [comment]
Fixed in 8.1.1. Again, thanks for your efforts!

**Comment by Jason3S** [comment]
@d-fischer,

Thank you for fixing it.
