### ISSUE TITLE
way to save configuration 

### ISSUE THREAD

**Issue by Araxeus** [cosmiconfig/cosmiconfig#301]
Say my-app loaded its config, then the user input some command like `my-app config set X=Y`

Now my-app wants to save the updated config

It seems that currently my-app would need to act on Result.filepath, so it needs to check if it's a package.json or some other file and write all the update logic itself

Would be nice to have a function to update the found config file

**Comment by d-fischer** [comment]
You can't really have broad format compatibility **and** writing support. For example, how would you even start trying to write to a potentially infinitely complex `.js` file?

I'd recommend a more specialized package like [conf](https://www.npmjs.com/package/conf), which completely abstracts away the storage, if you need to support writing back to your configuration.
