### ISSUE TITLE
First use of nullish coalescing ? Intended to give up on Node12?

### ISSUE THREAD

**Issue by cefn** [cosmiconfig/cosmiconfig#302]
A colleague noticed this line change a couple of days ago...

https://github.com/cosmiconfig/cosmiconfig/blob/17f5edc71d718c0c573d6700022858cc6cd6b21d/src/index.ts#L127

This is the first use of nullish coalescing in the project...

```
➜  cosmiconfig git:(main) git grep -E '\?\?' .
src/index.ts:  const overrideOptions = metaConfig.config ?? {};
```

In combination with the transpiler's target ES version, pipelines with a cosmiconfig dependency that were tested to include a backward-compatible node12 target (and that worked before this line was added) just started failing.

![image](https://user-images.githubusercontent.com/159819/226304673-18d8ba4b-520e-4b41-bc55-6f7676b42b8c.png)

Would you consider maintaining compatibility with a Node12 target. I know cosmiconfig is only tested in Node14, but at least some dependent projects, that treat cosmiconfig as a dependency rather than bundling it, were working in Node12 until this line change. 

Hopefully this could be achieved by just having an older Node target in the [babel config](https://github.com/cosmiconfig/cosmiconfig/blob/dee5198fd96c3f64b8b004cca9117f06aafe1212/package.json#L81), rather than holding back on using modern Typescript features.

**Comment by d-fischer** [comment]
cosmiconfig already doesn't install in node 12 (unless you choose to ignore the engines) since 8.0.0: https://github.com/cosmiconfig/cosmiconfig/blob/dee5198fd96c3f64b8b004cca9117f06aafe1212/package.json#L124-L126

Also, node 12 has been out of support for almost a year.

Please consider upgrading node instead.
