### ISSUE TITLE
Patch v7 for yaml vuln 

### ISSUE THREAD

**Issue by TannerS** [cosmiconfig/cosmiconfig#303]
Wondering if a patch will be appliedto v7 version for https://security.snyk.io/package/npm/yaml?

**Comment by d-fischer** [comment]
The report says that only the 2.x line is affected by that vulnerability. cosmiconfig v7 [is using `^1.10.0`](https://github.com/cosmiconfig/cosmiconfig/blob/18f14419aa7015aad11b7dc684947dec7171a9c5/package.json#L113) and thus isn't affected.

**Comment by davidrunger** [comment]
@TannerS : I was getting a dependabot security alert from GitHub saying "Dependabot cannot update yaml to a non-vulnerable version" and blaming `cosmiconfig`, even though this is not `cosmiconfig`'s fault, as @d-fischer noted.

In my repo, I had both `yaml` 1.x (via `cosmiconfig`) and `yaml` 2.x (from other dependencies). For some reason, `yarn upgrade yaml` wouldn't update the `yaml` 2.x version from `2.1.3` to `2.2.2`, even though it seemed to me that it should have been able to.

What I did was to delete `yarn.lock` and then run `yarn install` (which regenerated `yarn.lock` with a big diff vs what it was before). This gave me `yaml@2.2.2`, resolving the dependabot alert. I hope that this might help you, too.
