### ISSUE TITLE
Feature request: Read whole module if there is no default export

### ISSUE THREAD

**Issue by tianyingchun** [cosmiconfig/cosmiconfig#308]
https://github.com/cosmiconfig/cosmiconfig/pull/283#issuecomment-1575969971
```ts
const loadJs: LoaderAsync = async function loadJs(filepath) {
  try {
    const { href } = pathToFileURL(filepath);
    return (await import(href)).default;
  } catch (error) {
    return loadJsSync(filepath, null);
  }
};

```
return (await import(href)).default; always return undefined for project if we have an `named exports` at `xxx.config.js`

consider below example
`valid.config.js`

import { defineConfig } from 'vite';

// it is `esm` module causeof type:`module`
export const test = defineConfig({
  cake: 'a lie',
});

it will aways return me undefined.

maybe it should be 
```
const { href } = pathToFileURL(filepath);
const moduleData =  await import(href);
return moduleData.default|| moduleData;
```

**Comment by tianyingchun** [comment]
@beerose

**Comment by d-fischer** [comment]
I don't see why it should load a non-default export from the file. Do you have any actual use case for this? I'm pretty sure that vite does not use cosmiconfig.

**Comment by tianyingchun** [comment]
for convenient and fast, in some times we should defined `xxxx.mjs` 

it use `export const xx =xxx`, instead use 
`export default {
     xx:```
  }
`
cause of in `type:module`, `resoltion:nodenext` it not recommend use `export default xxxx`

**Comment by d-fischer** [comment]
That's a feature request then, not a bug.

**Comment by tianyingchun** [comment]
when this feature will be plan? :)

**Comment by prisis** [comment]
Hey @tianyingchun :), every open source project accepts a PR with the needed feature/bug ;)

**Comment by tianyingchun** [comment]
:) ok, i make time to make PR 💯

**Comment by jrandolf** [comment]
We use `default` exports because it semantically shows there is one configuration. Named exports has the implication of many which is very much against the simplicity we strive for in this package. Unless there is a well-defined use-case with production code available, we will probably not support this.
