### ISSUE TITLE
error - ./node_modules/cosmiconfig/dist/readFile.js:9:0 Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by luohao123** [cosmiconfig/cosmiconfig#310]
error - ./node_modules/cosmiconfig/dist/readFile.js:9:0
Module not found: Can't resolve 'fs'

**Comment by d-fischer** [comment]
A bit more context would be helpful. What environment are you trying to run in? (cosmiconfig only runs in node and there are no plans to change that.)
