### ISSUE TITLE
metaConfig.config ?? {}; 

### ISSUE THREAD

**Issue by kiranpattar** [cosmiconfig/cosmiconfig#314]
SyntaxError: Unexpected token '?'

Bamboo has latest postcss and webpack 5
node as 14.x

not able to compile in bamboo.
Please

**Comment by jrandolf** [comment]
Sorry, there is not enough information here to debug this. Please provide more information about your set up.

**Comment by kiranpattar** [comment]
ERROR in ./node_modules/@ckeditor/ckeditor5-ui/theme/components/labeledfield/labeledfieldview.css (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].use[2]!./node_modules/@ckeditor/ckeditor5-ui/theme/components/labeledfield/labeledfieldview.css)
--
04-Sep-2023 04:48:01 | Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
04-Sep-2023 04:48:01 | /home/bamb

**Comment by kiranpattar** [comment]
if (metaConfig.config?.loaders) {
--
04-Sep-2023 04:48:01 | ^
04-Sep-2023 04:48:01 |  
04-Sep-2023 04:48:01 | SyntaxError: Unexpected token '.'
04-Sep-2023 04:48:01 | at wrapSafe (internal/modules/cjs/loader.js:1072:16)
04-Sep-2023 04:48:01 | at Module._compile (internal/modules/cjs/loader.js:1122:27)
04-Sep-2023 04:48:01 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
04-Sep-2023 04:48:01 | at Module.load (internal/modules/cjs/loader.js:1002:32)
04-Sep-2023 04:48:01 | at Function.Module._load (internal/modules/cjs/loader.js:901:14)
04-Sep-2023 04:48:01 | at Module.require (internal/modules/cjs/loader.js:1044:19)
04-Sep-2023 04:48:01 | at require (internal/modules/cjs/helpers.js:77:18)
04-Sep-2023 04:48:01 | at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CMSG-NLFSNAPSHOT19-JOB1/kiwi/src/main/ux/node_modules/postcss-loader/dist/utils.js:18:20)
04-Sep-2023 04:48:01 | at Module._compile (internal/modules/cjs/loader.js:1158:30)
04-Sep-2023 04:48:01 | at Object.Module._extensions
