### ISSUE TITLE
Node.js version breaking change

### ISSUE THREAD

**Issue by eranshmil** [cosmiconfig/cosmiconfig#320]
Hey, thanks for all your work on this project!

In `v8.3.0` the supported `Node` versions changed to [v18](https://github.com/cosmiconfig/cosmiconfig/commit/2f0a25bae93e3c162607971e3a4522399b13d2af#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R135) and it's a breaking change and causes build to fail in `Node v16` environments.
Is that intentional? This package doesn't support `< v18` anymore?

```shell
error cosmiconfig@8.3.2: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.0"
error Found incompatible module.
```

**Comment by L-U-C-K-Y** [comment]
I experience the same issue, I'm trying to set manual resolution.

**Comment by d-fischer** [comment]
I am reverting this now. There have been a huge deal of infrastructure changes without any discussion as well.
