### ISSUE TITLE
Why does cosmiconfig require Node version greater than 18.0.0?

### ISSUE THREAD

**Issue by Hao-yiwen** [cosmiconfig/cosmiconfig#322]
cosmiconfig@8.3.2 requires Node version greater than 18.0.0. Many packages in the project depend on cosmiconfig, but the project is built using Node 16, leading to a build failure.

**Comment by EranClientside** [comment]
Duplicate of https://github.com/cosmiconfig/cosmiconfig/issues/320.
Already fixed in `v8.3.3`.

**Comment by eranshmil** [comment]
Duplicate of https://github.com/cosmiconfig/cosmiconfig/issues/320.
Already fixed in `v8.3.3`.

**Comment by d-fischer** [comment]
> Duplicate of #320. Already fixed in `v8.3.3`.

Yeah, that. Closing.
