### ISSUE TITLE
Regression in v8.3.x - missing json config file doesn't always return null

### ISSUE THREAD

**Issue by ghiscoding** [cosmiconfig/cosmiconfig#325]
The PR #311 seems to be causing some problems when trying to update cosmiconfig to v8.3.x in Lerna-Lite, I got a few failing unit tests as shown in this Renovate https://github.com/lerna-lite/lerna-lite/pull/713 which is failing.

What I can see is that the behavior changed if we compare new release v8.3.x with version prior to this release, it used to return an empty object but now it returns `undefined` as per this failing test (see PR [failure](https://github.com/lerna-lite/lerna-lite/actions/runs/6079288277/job/16491580280?pr=713) for reference)

```sh
 FAIL  packages/core/src/project/__tests__/project.spec.ts > Project > .config > defaults to an empty object
AssertionError: expected undefined to deeply equal {}

- Expected: 
Object {}

+ Received: 
undefined

 ❯ packages/core/src/project/__tests__/project.spec.ts:84:36
     82|       await initFixture('no-lerna-config');
     83| 
     84|       expect(new Project().config).toEqual({});
       |                                    ^
     85|     });
```
was that behavior really intended because I assume that could break some users of Lerna/Lerna-Lite unless I make code change. Take for example this other unit test that failed

```sh
TypeError: Cannot read properties of undefined (reading 'command')
 ❯ InitCommand.configureOptions packages/core/src/command.ts:196:47
    194|   configureOptions() {
    195|     // Command config object normalized to 'command' namespace
    196|     const commandConfig = this.project.config.command || {};
       |                                               ^
    197| 
    198|     // The current command always overrides otherCommandConfigs
 ❯ packages/core/src/command.ts:85:37
```
I would have to change it to use optional chaining to avoid failure
```diff
- const commandConfig = this.project.config.command || {};
+ const commandConfig = this.project.config?.command ?? {}; 
```

This behavior change (to return `undefined` instead of an empty object) is unexpected since the latest version was a `minor` version

**Comment by ghiscoding** [comment]
This issue was created as per comment in PR #311

> this PR #311 seems to be causing some problems when trying to update cosmiconfig to v8.3.x in Lerna-Lite, I got a few failing unit tests as shown in this Renovate https://github.com/lerna-lite/lerna-lite/pull/713 which is failing. Are there anything I need to change on my side in order to support this? cc @d-fischer

> @ghiscoding It seems like when there is no file, it does not return null anymore in your case. I have tried to construct a failing test against this, but I always get null where I should be. Could you please assist with figuring out specifics and then create a new issue for this?

**Comment by d-fischer** [comment]
The actual issue seems to be the other way around:

https://github.com/lerna-lite/lerna-lite/blob/65f81bbc848529550824c7d1a802adaa6095280c/packages/core/src/project/project.ts#L65C34-L66

Apparently, lerna-lite assumes a falsy result, which does not happen in this case for some reason. In my tests, cosmiconfig returns `null` when no configuration file is found though. I need to reproduce the circumstances where `null` is __not__ returned.

**Comment by ghiscoding** [comment]
oh damn you're right, that was written by the original author of Lerna years ago. The failing test shown on top has a fixture name of `no-lerna-config` so I could assume (without looking at the code) that the file doesn't exist

**Comment by ghiscoding** [comment]
could it be that it walks up the tree and returns `lerna.json` config file from Lerna-Lite instead of the actual fixture folder [`/__fixtures__/no-lerna-config`](https://github.com/lerna-lite/lerna-lite/tree/main/packages/core/src/project/__fixtures__/no-lerna-config) where it is suppose to look for? 

I'm currently on the work computer, I'll verify this in a couple of hours but I thought that might be a possibility

**Comment by ghiscoding** [comment]
So I ran the unit test debugger and I see that it doesn't go at all in the `transform` callback, in fact it doesn't break in any of my breakpoints that I have on `loaders`, `transform` and not even `catch`, it just goes straight trough

![image](https://github.com/cosmiconfig/cosmiconfig/assets/643976/aacc6910-8dfa-49ad-bc5a-61cfd8b2b8cf)

**Comment by jrandolf** [comment]
`cosmiconfig` travels up from the given file path (in `search`) until it reaches the home directory (if ever). The test should be using `stopDir` to define where to stop, in this case [`/__fixtures__/no-lerna-config`](https://github.com/lerna-lite/lerna-lite/tree/main/packages/core/src/project/__fixtures__/no-lerna-config).

**Comment by d-fischer** [comment]
8.3.5 should fix this. The issue was that `null` was never passed to `transform` with the refactored code.

**Comment by ghiscoding** [comment]
yup that did the trick, thanks for the fix :)
