### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by DanMoran-Lunio** [cosmiconfig/cosmiconfig#326]
Hi,

I wonder if you can help. I've got an error when building my application. Only occurring on my machine, others with the same code base and dependencies do not have this issue. We're a bit stuck with how to proceed with it, wondering if you've come across this problem before or anything similar?

OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn
npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm

Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ../../node_modules/postcss-loader/dist/cjs.js):
/home/dan/frontend/node_modules/postcss-loader/node_modules/cosmiconfig/dist/index.js:78
    if (metaConfig.config?.loaders) {
                          ^
SyntaxError: Unexpected token '.'

Thanks

**Comment by d-fischer** [comment]
It seems like you need to update some of your webpack loaders (probably postcss-loader), which seem to not support all syntax elements that node 14+ supports.

Please provide feedback on whether that helps.

**Comment by DanMoran-Lunio** [comment]
Cheers for coming back to me. Fixed it. It was nothing to do with the code stack. We use sudo to run the app and my version there had somehow been downgraded to v12. I thought all users were on v18.
