### ISSUE TITLE
Lerna-Lite project having an empty `.config.json` file gets picked up by cosmiconfig and is unexpected - behavior changed after 8.0 

### ISSUE THREAD

**Issue by ghiscoding** [cosmiconfig/cosmiconfig#329]
Someone opened this issue in Lerna-Lite ["bug: empty .config.json file in project root gets picked up as lerna-lite config"](https://github.com/lerna-lite/lerna-lite/issues/729) and this was not a problem with v8.0.0 and below, the behavior changed with v8.1.0 and higher.

Lerna/Lerna-Lite can only be configured in 2 ways, that is via a `lerna.json` file or the root `package.json` file and a "lerna" field inside it, anything else is irrelevant. Any `.config`, `.config.json` or whatever else should be discarded, that used to be the case in v8.0 and below, but the behavior changed in v8.1.0 and now it gets picked up and throws an error because the `.config.json` is empty and not parseable, but again we're not interested at all in these config types, so why is it being picked up?

### Reproduction
```sh
cd some-lerna-project-root-dir
touch .config.json # empty file
yarn lerna run 'echo hello' # or lerna version --dry-run
```

with cosmiconfig v8.0.0 it picks up `lerna.json` properly as it should and nothing else
![image](https://github.com/cosmiconfig/cosmiconfig/assets/643976/24d3579d-69bc-45bc-b117-412dafc53ca9)

but with v8.1.0 and higher, it picks up the `.config.json` file for some reason and Lerna-Lite internal code fails and throws an error because it totally is not expecting that file to be picked up and it throws because the file is empty and not parseable

![image](https://github.com/cosmiconfig/cosmiconfig/assets/643976/0ad2e1df-cfcd-4517-8b96-458db3f2b9b8)

That code was implemented by the original Lerna author and perhaps I misunderstood how cosmiconfig works but I taught that configuring `searchPlaces: ['lerna.json', 'package.json']` means that it would try to load config from these 2 files and nothing else, am I wrong? The code using cosmiconfig in Lerna-Lite is [here](https://github.com/lerna-lite/lerna-lite/blob/868f5f54d0715449d26acad99268f2604b5c74fa/packages/core/src/project/project.ts#L38-L82)

### Related Issues
At first I taught it was related to this other recent cosmiconfig issue [#313 - [Bug]: Config search fails if there is a file named .config](https://github.com/cosmiconfig/cosmiconfig/issues/313)

but since that didn't fix the problem, it's probably unrelated

### Alternative
downgrade to v8.0

**Comment by d-fischer** [comment]
9.0.0 will fix this. It's techincally a breaking change, as the search paths for our meta config file had to change, so we can't deliver a fix to this in a patch.

Can't give any guarantees on when 9.0.0 will release though.

**Comment by ghiscoding** [comment]
ok great, so I assume that you will provide some instructions on the breaking change, but in the case of Lerna-Lite project what will I have to change and will it make it work for all users of Lerna-Lite as well?

**Comment by d-fischer** [comment]
In order to "fix" this, a change on the user side is _necessary_ because cosmiconfig will not read `.config.json` (and other extensions of the same file basename) anymore. Instead, it will read `.config/config.json` etc. This should be communicated to users and should probably be delivered to users as a breaking change (major version bump) as well.

It should be low impact for you though, since you apparently never advertised the feature that used this to your users, but it is still breaking and should be treated as such.

**Comment by d-fischer** [comment]
You're misunderstanding the feature. *Anyone* can put their config in `.config.json`, regardless of the explorer options given by you. It is described in the second half of [the end user documentation section](https://github.com/cosmiconfig/cosmiconfig#usage-for-end-users).

Your regular config file does not need to move. But if your users used this cosmiconfig feature, they do need to adjust.

**Comment by ghiscoding** [comment]
I gave a try to v9-alpha.1 and everything works as expected, @d-fischer is there a changes left to do in v9? in short, should we expect an official release in the coming weeks? Thanks for all the great work.

**Comment by d-fischer** [comment]
I'm currently kinda swamped, but I should probably be able to finalize the last few changes I wanted to do this weekend, then I'll push another alpha. If everything is fine with that, I'll probably push the final version 9.0.0 about 2 weeks later.

**Comment by ghiscoding** [comment]
No worries, I just wanted to ping you in case you forgot, there's no rush per say, but of course it would be nice to eventually close the Lerna-Lite issue associated with this... Again no rush, it's just a ping, cheers 😉 

Thanks for everything
