### ISSUE TITLE
Add link to Python port of Cosmiconfig

### ISSUE THREAD

**Issue by JuroOravec** [cosmiconfig/cosmiconfig#330]
Hi, I used Cosmiconfig in some of my JS/TS projects. I'm now writing a Python package, and I missed the flexibility of Cosmiconfig. Seeing that Cosmiconfig is only 6 files (not counting the test files), I decided to port it to Python. ChatGPT definitely made the whole thing easier, and it took about 15 hours altogether (including also 2 test files).

Project: https://github.com/JuroOravec/pycosmiconfig
PyPI: https://pypi.org/project/pycosmiconfig/

I wanted to ask if there could be a section in README that would mention Pycosmiconfig? So that people will know that they can still use Cosmiconfig even in Python :)

**Comment by d-fischer** [comment]
I don't think it is a common case that a Python user stumbles upon the Cosmiconfig repo or npm page to find out they can use this. Also, I have not reviewed any of the code myself, since I do not know enough Python, but I can not endorse anything that seems to be mostly a product of ChatGPT. Closing.

**Comment by JuroOravec** [comment]
Thanks for getting to this quickly!

IMO that's a wrong way to think about it. The port is intended for people who already use / know of cosmiconfig, but also work with python and would like to stick with their favorite setup.

And please don't devalue my effort by saying that it's "mostly product of Chatgpt". My Chatgpt comment was meant as a cheeky one, but it seems it didn't land.

I still had to go though all the files, understand them, and then fix them. The port is also covered by tests. I had to recreate the testing env (with the unique temp dir per test) and rewrite the tests.

I'm happy to take you through the code / live demo if that's the concern.
