### ISSUE TITLE
README doesn't mention .mjs files inside of a config directory

### ISSUE THREAD

**Issue by haykam821** [cosmiconfig/cosmiconfig#331]
The documentation in the README seems to be inconsistent with the actual functionality, where `./config/${moduleName}.mjs` is a valid path, which seems like a mistake to me. The omission can particularly be seen on the following lines:

https://github.com/cosmiconfig/cosmiconfig/blob/42ca3fab6d6ae593a895c0fe4e2a5f6b297e6361/README.md#L23 https://github.com/cosmiconfig/cosmiconfig/blob/42ca3fab6d6ae593a895c0fe4e2a5f6b297e6361/README.md#L152 https://github.com/cosmiconfig/cosmiconfig/blob/42ca3fab6d6ae593a895c0fe4e2a5f6b297e6361/README.md#L282-L288 https://github.com/cosmiconfig/cosmiconfig/blob/42ca3fab6d6ae593a895c0fe4e2a5f6b297e6361/README.md#L572-L578

There may be some other examples that I missed.

**Comment by d-fischer** [comment]
Thanks for spotting!
Fixed on v9 branch; as I don't think this is very critical, since many consumers override this anyway, it can wait until the next major release.
