### ISSUE TITLE
Module "typescript" possibly misplaced as a dev dependency

### ISSUE THREAD

**Issue by DLFDK** [cosmiconfig/cosmiconfig#335]
It's appears as though the module typescript has been misplaced as a dev dependency rather than a regular dependency, causing a failure if the user doesn't already have typescript installed. 

From the dist folder:

    node_modules/cosmiconfig/dist/loaders.js:91:35:
      91 │         typescript = (await import('typescript')).default;

**Comment by d-fischer** [comment]
It is listed as an optional peer dependency as well. This means that if you want to import .ts config files, you must install typescript yourself.
