### ISSUE TITLE
cosmiconfig requires at least version 4 of Node, please upgrade

### ISSUE THREAD

**Issue by linlinyang** [cosmiconfig/cosmiconfig#336]
Here is a error, 'cosmiconfig requires at least version 4 of Node, please upgrade' for version of node 16.20.2.
And install all version of cosmiconfig throw this error.
And version of node to 14.21.3, 20.5.1 failed

**Comment by d-fischer** [comment]
cosmiconfig does not output such error messages, that's probably your package manager. The two most likely scenarios are:

- Your package manager has a bug, or
- (much more likely) you have multiple node versions installed on your system, and your package manager runs on a very old one.

Neither of these are a concern of cosmiconfig, so I'm closing this issue.
