### ISSUE TITLE
Please release source code to npm if you release source map files

### ISSUE THREAD

**Issue by tylerlong** [cosmiconfig/cosmiconfig#337]
For now, only the dist folder is released. There is source map file released. 

For example: `util.d.ts`:

```
{"version":3,"file":"util.d.ts","sourceRoot":"","sources":["../src/util.ts"],"names":[],"mappings":""}
```

It causes a error/warning in my Parcel built project:

```
[Error: ENOENT: no such file or directory, open '/Users/tyler.liu/src/ts/ttpt-electron-demo/node_modules/src/util.ts']
```

This error only appears the first time I run the parcel command. It doesn't break anything.
But still, I hope we could address this issue.

**Comment by d-fischer** [comment]
I fixed this (by removing the source maps from the package publishing), but as you're saying, it's just a warning and doesn't break anything. I will release the fix with the next due version.
