### ISSUE TITLE
Meta config files are not looked in cwd anymore? (in v9 changelog but not in README

### ISSUE THREAD

**Issue by JounQin** [cosmiconfig/cosmiconfig#339]
v9 Changelog: https://github.com/cosmiconfig/cosmiconfig/blob/main/CHANGELOG.md#900

> Breaking change: Meta config files (i.e. config.js and similar) are not looked for in the current working directory anymore. Instead, it looks in the .config subfolder.

README:

> By default, Cosmiconfig will check the current directory for the following:
>
> - a package.json property
> - a JSON or YAML, extensionless "rc file"
> - an "rc file" with the extensions .json, .yaml, .yml, .js, .ts, .mjs, or .cjs
> - any of the above two inside a .config subdirectory
> - a .config.js, .config.ts, .config.mjs, or .config.cjs file

I don't quite sure to understand that would `x.config.js` in cwd still work on v9? I'll trying to understand whether can I upgrade to v9 safely.

**Comment by d-fischer** [comment]
Configuration files with names containing your tool name are not affected by this change. This is talking about an advanced end user feature described lower in the readme. You should relay this change to your end users when upgrading, and optimally do it only when you do a major version bump as well.

**Comment by d-fischer** [comment]
`config.js` files and files ending in `.config.js` are different things. The former is the aforementioned advanced feature, and the latter is just a regular tool config file. Only the former is affected.

**Comment by JounQin** [comment]
Oh.... I understand now! The leading dot is the key.

**Comment by d-fischer** [comment]
There is no leading dot in the latter. What I meant is files in the format of `yourtoolname.config.js`.

**Comment by JounQin** [comment]
I mean `config.js` is different `.config.js` in changelog that leading dot is the key. I was confused with this part.
